name: expect_error
description: A testing utility for checking compilation errors
version: 1.0.10
repository: https://github.com/rrousselGit/expect_error

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  analyzer: ^8.1.0
  build_test: ">=2.1.3 <4.0.0"
  collection: ^1.15.0
  package_config: ^2.0.0
  path: ^1.9.1
  pubspec_parse: ^1.5.0
  stack_trace: ^1.10.0
  test: ^1.26.3

dev_dependencies:
  test_api:
  test_core:
